### ISSUE TITLE
Trilinear interpolation from grid to point cloud - New feature request

### ISSUE THREAD

**Issue by decadenza** [tedyhabtegebrial/PyTorch-Trilinear-Interpolation#2]
Suppose I have a uniformly spaced grid with some optional features and I need to interpolate those to a point cloud (non uniformly spaced). This should be the opposite of your code:
For example (1D) going from 0, 1, 2, 3 to the non uniform points 0.1, 0.8, 1.3, 1.8

Would it be possible with some modification of the code?

Thanks
Cheers

**Comment by tedyhabtegebrial** [comment]
Hi @decadenza,

For some reason I missed the notification. I think interpolating a regular 3D grid with a point cloud should be possible.
Let me know if you still care about this issue so that I can take a look.

**Comment by decadenza** [comment]
Thanks for the reply. I moved forward now, but I'll keep your code for future implementation.
